---
- name: Deploy Dockerized Website on EC2
  hosts: web
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to Docker Hub
      shell: |
        echo "{{ docker_pass }}" | docker login -u {{ docker_user }} --password-stdin
      args:
        executable: /bin/bash

    - name: Pull Docker image
      shell: docker pull {{ docker_user }}/websiiteimage:latest

    - name: Stop and remove existing container
      shell: |
        docker rm -f website || true
      args:
        executable: /bin/bash

    - name: Run the Docker container
      docker_container:
        name: website
        image: "{{ docker_user }}/websiiteimage:latest"
        state: started
        ports:
          - "80:80"
        restart_policy: always
