---
- name: Deploy Dockerized Website on EC2
  hosts: web  # Reference the group defined in your inventory file
  become: true
  vars:
    docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
    docker_pass: "{{ lookup('env', 'DOCKER_PASS') }}"
    image_name: "websiteimage:latest"
  
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io  # Use docker.io for Ubuntu's package
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_user }}/{{ image_name }}"
        state: present
        pull: yes

    - name: Stop and remove existing container
      docker_container:
        name: website
        state: absent

    - name: Run the Docker container
      docker_container:
        name: website
        image: "{{ docker_user }}/{{ image_name }}"
        state: started
        ports:
          - "80:80"
        restart_policy: always
