- name: Deploy Dockerized Website
  hosts: web
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Log in to Docker Hub
      shell: |
        echo "{{ docker_pass }}" | docker login -u "{{ docker_user }}" --password-stdin
      args:
        executable: /bin/bash

    - name: Pull and run the Docker container
      docker_container:
        name: website
        image: "{{ docker_user }}/websiiteimage:latest"
        state: started
        ports:
          - "80:80"
        recreate: true
