---
- name: Deploy Dockerized Website on EC2
  hosts: web
  become: true
  tasks:

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy Docker image to EC2
      copy:
        src: websiiteimage.tar
        dest: /tmp/websiiteimage.tar

    - name: Load the Docker image
      shell: docker load < /tmp/websiiteimage.tar

    - name: Stop and remove any existing container
      shell: |
        docker rm -f website || true
      args:
        executable: /bin/bash

    - name: Run the Docker container
      docker_container:
        name: website
        image: "websiiteimage:latest"
        state: started
        ports:
          - "80:80"
        restart_policy: always
